permalink: /:year/:month/:day/:title
url: risograph.xyz

# variables
title: "risograph"
description: wharever bro...
google_verification: null

future: true

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
#kramdown:
#  input: GFM
#  syntax_highlighter_opts:
#    disable : true

# Icons
icons:
  articles: file.ico
  crosswords: crossword.png